Lösungen Woche 4
dhbw-ma-ppp/ppp-2023 pull request #102
Opened 2023-11-01 16:19 UTC by s231365

Please review:
solution to task: 16694270

2023-11-02 21:37 UTC, TrueEsel approved these changes
All in all the code is doing its job

2023-11-02 21:37 UTC, TrueEsel commented on Exercises/LauravanUffelt/VL 4 Lösungen.py
> +                return None
you could also write something like "exit(0)" to immediately stop the program instead of returning none

2023-11-02 21:37 UTC, TrueEsel commented on Exercises/LauravanUffelt/VL 4 Lösungen.py
> +        return intake[element] if mode == 0 else element
nice way to deal with the different read modes

2023-11-02 21:37 UTC, TrueEsel commented on Exercises/LauravanUffelt/VL 4 Lösungen.py
> +        match opcode:
im not sure if writing the whole logic for the operations into a match case statement is a good idea, even though its clearly working. You could use an dictionary with the required operations instead

2023-11-02 21:37 UTC, TrueEsel commented on Exercises/LauravanUffelt/VL 4 Lösungen.py
> +    def opcodes(count):
In my opinion this name is a bit confusing since your whole logic is in this method. I'd expect that something with the name opcodes would only deal with processing an opcode, not executing all of the calculations.

2023-11-02 21:37 UTC, TrueEsel commented on Exercises/LauravanUffelt/VL 4 Lösungen.py
> +        if isinstance(result, int):
I dont understand what the logic from line 119 to 123 is supposed to achieve, since we dont need to return anything. I tried replacing these lines with "count = opcodes(count)" and it still worked.

2023-11-02 22:20 UTC, thecodingcube77 requested changes
A proper halt to the program is not implemented at all. It only worked because the halt opcode is positioned at the second last index of the array passed to the function. If it would have been anywhere earlier you would have realized what the problem is.

2023-11-02 22:20 UTC, thecodingcube77 commented on Exercises/LauravanUffelt/VL 4 Lösungen.py
> +        if isinstance(result, int):
I think the idea is, that the opcode 99 returns `None`, which is no instance of `int`. But the else does nothing so the opcode 99 would get skipped I think. But the opcode 99 gets never reached because of the `len(intake) - 2` in line 117. The `- 2` should not be there. You probably added it because you got an `IndexError` in line 53. With some logic in place to stop the error from halting the execution the program reaches the opcode 99, your count gets set to `None` but you don't do anything in the else in line 122. This causes the program to end up in an endless loop. Not good. Line 122 should contain some code to properly halt the program.

2023-11-03 09:25 UTC, thecodingcube77 requested changes
The code could still run into an error with a different array of commands with opcode 99 in the last place. This is due to the access to `intake[count + 1]` in line 52.
You also execute some code in every loop which actually is not needed for all the opcodes (the determination of (2)modes). 
For duplicate code the migration to a separate function is always a good idea.

2023-11-03 09:25 UTC, thecodingcube77 commented on Exercises/LauravanUffelt/VL 4 Lösungen.py
> +                element2 = element_value(mode[1], intake[count+2])
Moving this line into the cases where it's needed creates much duplicate code. It could be placed in a function as suggested in my other comment. Duplicate code provokes bugs if you want to change something as you could forget to do the change in one place.

2023-11-03 09:25 UTC, thecodingcube77 commented on Exercises/LauravanUffelt/VL 4 Lösungen.py
> +        count = opcodes(count)
This is way better.

2023-11-03 09:25 UTC, thecodingcube77 commented on Exercises/LauravanUffelt/VL 4 Lösungen.py
>          mode = [int(digit) for digit in operation[:-2]][::-1]
You don't really need to determine the modes every time as not every opcode requires modes, could also be placed into a separate function.

2023-11-03 16:07 UTC, thecodingcube77 reviewed
Everything is good now in my opinion. Requested changes successfully implemented.

2023-11-03 16:07 UTC, thecodingcube77 approved these changes
Well I should also approve

2023-11-09 07:41 UTC, merged