Celina 4
dhbw-ma-ppp/ppp-2023 pull request #106
Opened 2023-11-02 20:34 UTC by CelinaRiegel

The output was 16694270

2023-11-02 21:17 UTC, LeMixer requested changes
The code is working and yielding the correct result. You can implement my suggestions if you want, but some things like the misleading `first_pos` parameter should be changed. Also fix your folder structure. It seems like you accidentally created a new folder and uploaded your results there.

2023-11-02 21:17 UTC, LeMixer commented on Exercises/Celina/exercises_04.py
> +                if jump_if_true(commands[first],commands[second]) != False:
Try to avoid calling the same function twice with the same parameters. Consider using the walrus operator or at least execute the function before the if statement and then check if `i` is true afterwards. Furthermore why not check if the condition is `True` and not if it is `not False`?

2023-11-14 18:08 UTC, kuckuk3 requested changes

2023-11-14 18:12 UTC, ClasherKasten requested changes
Please do not hinder yourself from adding type annotations to your code, It'd be really useful.

2023-11-14 18:12 UTC, ClasherKasten commented on Exercises/Celina/exercises_04.py
> +        return 0
this whole function can be substituted by a simple
```python
int(first_pos == second_pos)
```

2023-11-14 18:12 UTC, ClasherKasten commented on Exercises/Celina/exercises_04.py
> +def wierd_computer(commands):
typo in function name. probably should be `weird_computer`

2023-11-14 20:11 UTC, ClasherKasten requested changes
Old comments still apply.

2023-11-14 20:11 UTC, ClasherKasten commented on Exercises/Celina/exercises_04.py
> +                if jump_if(commands[first],commands[second]) == True:
`== True` is unnecessary in this context. Just remove it.

2023-11-18 09:33 UTC, atrejut commented
@CelinaRiegel please try to get this old PR merged

2023-11-18 14:50 UTC, LeMixer approved these changes

2023-11-21 07:50 UTC, merged