Woche 04 aufgaben
dhbw-ma-ppp/ppp-2023 pull request #107
Opened 2023-11-02 21:17 UTC by TomKnoden

2023-11-02 21:48 UTC, thecodingcube77 requested changes
First of all you did not state what your output was in your pull request. Please change that.

Otherwise the solution seems almost okay to me. You got really much duplicate code which you could try to remove in some way (that is not mainly what stops me from approving, just a general comment).

The problems can be seen in detail in the other comments.

2023-11-02 21:48 UTC, thecodingcube77 commented on Exercises/Tom_Knoden/Woche04/Woche_04_Aufgaben.py
> +            param1 = programm[position + 1] if modus1 == 1 else programm[programm[position + 1]]
You could leave out the `== 1` as anything non zero is interpreted as `True`

2023-11-02 21:48 UTC, thecodingcube77 commented on Exercises/Tom_Knoden/Woche04/Woche_04_Aufgaben.py
> +eingabe = int(input("Geben Sie die Eingabe (z.B. 5) ein: ")
The input should be in the `bearbeite_programm()` function under opcode 3. This is problematic as there could possibly be more than one input.

2023-11-02 21:48 UTC, thecodingcube77 commented on Exercises/Tom_Knoden/Woche04/Woche_04_Aufgaben.py
> +            programm[programm[position + 1]] = eingabe
The input should happen here inside of the function.

2023-11-02 21:48 UTC, thecodingcube77 commented on Exercises/Tom_Knoden/Woche04/Woche_04_Aufgaben.py
> +            ausgabe.append(programm[programm[position + 1]] if modus1 == 0 else programm[position + 1])
The value should be printed here and not added to an array.

2023-11-18 09:33 UTC, atrejut commented
@TomKnoden please try to get this old PR merged

2023-11-28 22:30 UTC, closed without merging