Exercise 4
dhbw-ma-ppp/ppp-2023 pull request #119
Opened 2023-11-05 16:57 UTC by RubelOS

Task 1
5 + 16 = 21

Task 2
6261

2023-11-06 19:25 UTC, thecodingcube77 requested changes
What you need to do is fixing the first task as your result is clearly wrong. The other comments are more of suggestions.

2023-11-06 19:25 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_05.py
> +    fp = open("data\input_sequence.txt", 'r')
You should consider using pathlib. I was unable to run this file on Linux due to the `\` in the Windows path.

2023-11-06 19:25 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_05.py
> +                    return f"{numbers[iteratorThroughSmallSteps]} + {numbers[iteratorThroughSmallStepsTwo]} = {numbers[iteratorThroughBigSteps]}"
Your result of 21 is wrong. I think you understood the task in a wrong way. What you did is checking for the first pair of numbers that add up to the 27th number(also wrong, should be 26th) and end the execution there. But you should actually search for the first number that is not a sum of any 2 numbers in the 25 before it.
The step of 26 is also not correct as you now only check every 26th number but you should check every number(except for the first 25 as they don't have 25 numbers before them).
Next point. This code is very unreadable in my opinion. It took me quite some time to understand fully. Might be worth restructuring.
Ways to fix/improve:
    - Turn the 26's into 25's
    - Remove the step size
    - Change the if, that it now checks if no pair in your 25 numbers sums up to the given number

2023-11-06 19:25 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_05.py
> +    lines = fp.read().strip()
You can use
```py
with open('filepath') as file:
    # do your stuff here with the file
```
to automatically close the file after the code block

2023-11-06 19:25 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_05.py
> +            statement_array.append(str(i[3:]))
This can be very easy and readable if you use regex. It is quite easy in this simple case.

2023-11-06 19:25 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_05.py
> +    statement_array = []
`statement` is a confusing name in this context in my opinion.

2023-11-06 19:25 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_05.py
> +    for i in range(0,len(statement_dict_array[0])):
When starting at `0` the `range()` function actually does not need a start value.

2023-11-07 09:11 UTC, RubelOS commented on Exercises/JuliusDralle/exercises_05.py
> +                    return f"{numbers[iteratorThroughSmallSteps]} + {numbers[iteratorThroughSmallStepsTwo]} = {numbers[iteratorThroughBigSteps]}"
The 26th Number is the first number which is being looked at

2023-11-07 09:43 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_05.py
> +                for iteratorThroughSmallStepsTwo in range(iteratorThroughBigSteps-26, iteratorThroughBigSteps):
The -26 in the start points for the ranges should be 25, because you only want to check the 25 numbers before. You include the index -1 in the first iteration of the outer for loop because of this. The result stays the same but he logic is not 100% correct at the moment.

2023-11-07 10:44 UTC, thecodingcube77 approved these changes

2023-11-09 15:31 UTC, atrejut commented
Approved by @thecodingcube77 even though the solution to task 2 is different from your own solution? Only one of you can be right :D

2023-11-09 18:52 UTC, RubelOS commented
All problems focusing on functionality were solved. I did not implement a dictionary but still continue using my own nested list

2023-11-09 19:41 UTC, thecodingcube77 requested changes
You don't need to change your data structure to a dictionary to make `countBags()` (still wrong format) work to return the right answer.

2023-11-09 19:41 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_05.py
> +print(countBags("shiny gold")-1)
I consider this a really hacky solution. You now require the user to always subtract 1 from the result of the function, as it actually does not return the correct answer by itself. This change just resulted from the knowledge of the correct solution but would not have been made in a scenario where the answer is unknown.

2023-11-21 10:18 UTC, RubelOS commented
I now use PathLib

2023-11-28 19:35 UTC, merged