PaulSeidel_Exercises05 (1639024365/ 6260) finished
dhbw-ma-ppp/ppp-2023 pull request #124
Opened 2023-11-08 18:30 UTC by paulseidel08

Task 1 finished, Task 2 not completely

Task 1 output: "the integer at sequence[653] = 1639024365 can't be build out of the 25 Integers in front of it!"

2023-11-08 20:23 UTC, thecodingcube77 commented on Exercises/PaulSeidel/PSeidel_exercises_05.py
> +        element_raw = list_of_lines[i]
You should do 
```py
for element_raw in list_ofLines
    # some stuff here
```
semantically the same but you don't need the index.

2023-11-09 09:36 UTC, RubelOS commented on Exercises/PaulSeidel/PSeidel_exercises_05.py
> +                    found_smth += 1
You could have negate this statement and return the solution directly, when an number is **not** being able to be built by the given requirements.

Fine solution for the fist task! Seemingly correct answer! Aweseome!

2023-11-09 09:36 UTC, RubelOS commented
Please add your result in the title of your pullrequest!

2023-11-09 09:39 UTC, RubelOS requested changes
Please finish task 2 (just marking it as request changes so it is clear for everyone)

2023-11-15 10:53 UTC, RubelOS approved these changes
Nice solution to both tasks!

2023-11-15 16:01 UTC, RubelOS commented on Exercises/PaulSeidel/PSeidel_exercises_05.py
> +def dictAllBags():
naming convention please!

2023-12-05 15:14 UTC, merged