Celina 5
dhbw-ma-ppp/ppp-2023 pull request #133
Opened 2023-11-09 18:53 UTC by CelinaRiegel

2023-11-12 13:09 UTC, TrueEsel approved these changes
The code ist pretty readable and does what its supposed to. I don't know if you did that on purpose but you're deleting the exercises one and two from your folder

2023-11-12 13:09 UTC, TrueEsel commented on Exercises/Celina/exercises_05.py
> +                    new_start_bag=bag[1] + "s"
Smart way to resolve the problem of having "bag" and "bags"

2023-11-14 23:55 UTC, ClasherKasten requested changes

2023-11-14 23:55 UTC, ClasherKasten commented on Exercises/Celina/exercises_05.py
> +text= open("data/input_sequence.txt","r")
Use a contextmanager.

2023-11-14 23:55 UTC, ClasherKasten commented on Exercises/Celina/exercises_05.py
> +bags= open("data/input_bags.txt","r")
Use a contextmanager.

2023-11-14 23:55 UTC, ClasherKasten commented on Exercises/Celina/exercises_05.py
> +                    new_start_bag=bag[1]
Use "Ternary" operator.

2023-11-21 07:51 UTC, merged