Woche05
dhbw-ma-ppp/ppp-2023 pull request #135
Opened 2023-11-09 23:22 UTC by TomKnoden

Lösungen zu den Aufgaben:
Nr.1) 1639024365
Nr.2)  6260

2023-11-13 09:36 UTC, paulseidel08 commented
Please write the outcomes of the exercises in the title of your pull request

2023-11-13 09:38 UTC, paulseidel08 commented
Don't put multiple Exercises in one pull request. e.g. the pull request of week 05 should only contain Exercise05

2023-11-13 18:09 UTC, paulseidel08 requested changes
Your Code for Exercises05 works totally fine and seems very efficient to me. Good Job!
Maybe you could add some docstrings next time, to make your code even more readable.

But for your code to be merged, you have to only put Exercise05 in your Pull Request. At the Moment, there are also the Exercises 04 and 03 included. For that I'm requesting changes. Also you should put the outcomes of your solutions in the title of your pull request.

2023-11-14 23:50 UTC, ClasherKasten requested changes
Overall good but missing type annotations.

2023-11-14 23:50 UTC, ClasherKasten commented on Exercises/Tom_Knoden/Woche05/Woche_05_Aufgaben.py
> +with open('data/input_sequence.txt', 'r') as file:
Not OS independent.

2023-11-14 23:50 UTC, ClasherKasten commented on Exercises/Tom_Knoden/Woche05/Woche_05_Aufgaben.py
> +bag_rules = parse_bag_rules('data/input_bags.txt')
Not OS independent.

2023-11-14 23:51 UTC, ClasherKasten requested changes

2023-11-14 23:51 UTC, ClasherKasten commented on Exercises/Tom_Knoden/Woche05/Woche_05_Aufgaben.py
> +        current_number = numbers[i]
Can be more pythonic using `enumerate(...)`

2023-11-17 09:04 UTC, closed without merging