Week 5 Utku Acikel
dhbw-ma-ppp/ppp-2023 pull request #136
Opened 2023-11-10 00:01 UTC by UtkuDHBW

Still missing comments, need to added!

Task 1: 1639024365 / Task 2: 6260

2023-11-14 18:54 UTC, kuckuk3 requested changes

2023-11-14 18:54 UTC, kuckuk3 commented on Exercises/Utku Acikel/exercises_05.py
> +"""
remove coment

2023-11-14 23:43 UTC, ClasherKasten requested changes
As with almost all reviews: type annotations are missing!

2023-11-14 23:43 UTC, ClasherKasten commented on Exercises/Utku Acikel/exercises_05.py
> +    except:
Do not use blank `except` as this can lead to errors being captured that shouldn't be.

2023-11-14 23:43 UTC, ClasherKasten commented on Exercises/Utku Acikel/exercises_05.py
> +        raise Exception("Error, can't find file. Change your custom working directory.")
Try to raise a more specific type of Exception.

2023-11-14 23:43 UTC, ClasherKasten commented on Exercises/Utku Acikel/exercises_05.py
> +"""
Either follow this suggestion or when intended as a docstring bring it to the appropriate place and into the appropriate format.

2023-11-15 12:02 UTC, FelixRegnier approved these changes
Insgesamt gute und übersichtliche Lösung wie immer

2023-11-15 12:02 UTC, FelixRegnier commented on Exercises/Utku Acikel/exercises_05.py
> +print(find_invalid_number())
Gute Lösung! 
Ich fände es allerdings besser, wenn numbers und preceding_length in der Funktion übergeben werden würde.

2023-11-15 13:08 UTC, CorvinAn97 commented
Overall  good solution. :)

2023-12-08 09:05 UTC, merged