Jonas-Week06 (1778099, 1623571)
dhbw-ma-ppp/ppp-2023 pull request #139
Opened 2023-11-13 08:17 UTC by DrKeks1010

Taks 1:
the total sum of all directories smaller than 100000 is 1778099

Task 2:
To make space for the file with a size of 30000000, something greater than 1609574 has to be deleted:
Found directory: bwmglvmt at \pcqjnl\lrrl\nwjggvr\bwmglvmt with a size of 1623571

2023-11-14 18:07 UTC, kuckuk3 requested changes

2023-11-14 18:07 UTC, kuckuk3 commented on Exercises/JonasPutz/exercises_06.py
> +delete_dir(_directory_tree, 30000000, 70000000)
no magic values

2023-11-14 23:28 UTC, ClasherKasten requested changes
Pretty nice solution, especially the type annotations are a big plus :+1:

2023-11-14 23:28 UTC, ClasherKasten commented on Exercises/JonasPutz/exercises_06.py
> +        raise NameError(f"Unknown directory {name}")
A more pythonic way would be to use `@property`.

2023-11-14 23:28 UTC, ClasherKasten commented on Exercises/JonasPutz/exercises_06.py
> +                line = line[2::]
Only `line[2:]` is needed.

2023-11-21 09:03 UTC, RubelOS approved these changes
Really good solution! Well done!

2023-11-29 16:44 UTC, merged