Raphael Fritz Woche 6 (1778099 1623571)
dhbw-ma-ppp/ppp-2023 pull request #141
Opened 2023-11-14 22:44 UTC by FritzRa

2023-11-14 23:20 UTC, ClasherKasten requested changes
Overall okay-ish, though some type annotations would be wonderful.

2023-11-14 23:20 UTC, ClasherKasten commented on Exercises/Raphael Fritz/Sechste Woche Aufgaben.py
> +        return sessionlist
This is essentially a list comprehension
```python
return [line.replace('\n', '') for line in file]
```

2023-11-14 23:20 UTC, ClasherKasten commented on Exercises/Raphael Fritz/Sechste Woche Aufgaben.py
> +from pathlib import Path
Why use `pathlib` if all you need it for is to pass it to `get_terminal_session`? Seems a bit bloated,

2023-11-14 23:20 UTC, ClasherKasten commented on Exercises/Raphael Fritz/Sechste Woche Aufgaben.py
> +    filepath = filepath + (sessionlist[index-1].replace("$ cd ","") + ("/"))
Not OS independent. Either make use of the imported `pathlib` or even better: use `os.path.join`.

2023-11-14 23:20 UTC, ClasherKasten commented on Exercises/Raphael Fritz/Sechste Woche Aufgaben.py
> +    filepath = "/".join(filepath.split('/')[0:-2]) + "/"
Not OS independent. Either make use of the imported `pathlib` or even better: use `os.path.join`.

2023-11-15 09:08 UTC, FritzRa commented on Exercises/Raphael Fritz/Sechste Woche Aufgaben.py
> +    filepath = filepath + (sessionlist[index-1].replace("$ cd ","") + ("/"))
the filepath in this function refers to the (fictional) filepath that is created when going through the session list, it therefore should have nothing to do with the OS.

2023-11-15 09:08 UTC, FritzRa commented on Exercises/Raphael Fritz/Sechste Woche Aufgaben.py
> +    filepath = "/".join(filepath.split('/')[0:-2]) + "/"
the filepath in this function refers to the (fictional) filepath that is created when going through the session list, it therefore should have nothing to do with the OS.

2023-11-15 09:13 UTC, ClasherKasten commented on Exercises/Raphael Fritz/Sechste Woche Aufgaben.py
> +    filepath = filepath + (sessionlist[index-1].replace("$ cd ","") + ("/"))
You're right, thought i had thrown away this idea/comment...

2023-11-15 09:35 UTC, FritzRa commented on Exercises/Raphael Fritz/Sechste Woche Aufgaben.py
> +    filepath = "/".join(filepath.split('/')[0:-2]) + "/"
I am also wondering:
https://github.com/dhbw-ma-ppp/ppp-2023/pull/142#issuecomment-1812010539

2023-11-22 11:37 UTC, FelixRegnier approved these changes
Insgesamt gute Loesung fuer die Aufgabe. Die Task-Funktionen wuerde ich allerdings nicht so hart coden.

2023-11-22 11:37 UTC, FelixRegnier commented on Exercises/Raphael Fritz/Sechste Woche Aufgaben.py
> +    return min(deletionlist)
Ich wuerde es bevorzugen, wenn die Grenzen fuer die Aufgaben als Argument uebergeben werden, ist in diesem Fall jedoch nicht falsch, da die Aufgabe es so vorgegeben hat

2023-11-24 07:39 UTC, merged