Gerrit Fritz Aufgabe 6 (1778099, 1623571)
dhbw-ma-ppp/ppp-2023 pull request #142
Opened 2023-11-15 07:56 UTC by GeFritz

2023-11-15 08:10 UTC, ClasherKasten requested changes
Almost good type annotations but types inheriting from `Generic` should have concrete types.

2023-11-15 08:10 UTC, ClasherKasten commented on Exercises/GerritFritz/exercises_06.py
> +class Directory():
Python 3 doesn't require the parentheses after the class name.

2023-11-15 08:10 UTC, ClasherKasten commented on Exercises/GerritFritz/exercises_06.py
> +        else: raise RuntimeError(f"No such dir: {folder}")
Please refrain from writing blocks like that. It's not very pythonic to do it, especially not to such an extent.

2023-11-15 08:10 UTC, ClasherKasten commented on Exercises/GerritFritz/exercises_06.py
> +print(get_mindir(size_dict,70000000, 30000000))
No magic values!

2023-11-15 08:22 UTC, GeFritz commented on Exercises/GerritFritz/exercises_06.py
> +print(get_mindir(size_dict,70000000, 30000000))
Could you please elaborate?

2023-11-15 08:23 UTC, GeFritz commented on Exercises/GerritFritz/exercises_06.py
> +        else: raise RuntimeError(f"No such dir: {folder}")
What exactly is the problem here? Is not merely a preference?

2023-11-15 08:29 UTC, ClasherKasten commented on Exercises/GerritFritz/exercises_06.py
> +print(get_mindir(size_dict,70000000, 30000000))
Someone without access to the assignment text shouldn't have to guess why exactly these values are chosen.

2023-11-15 08:31 UTC, GeFritz commented
Thank you for the insights. The change requests are helpful, but normally the classmates have to review and get grades. The problem now is that the others have to review code that already was reviewed. I never saw a pull request from you, so I assume that you aren't in our course?

2023-11-15 08:37 UTC, ClasherKasten commented on Exercises/GerritFritz/exercises_06.py
> +        else: raise RuntimeError(f"No such dir: {folder}")
You probably won't stumble a lot about productive code like that. Which in the end means for you to adapt to the new (way more common and standardized) pattern.

See [PEP8](https://peps.python.org/pep-0008/#other-recommendations)
> Compound statements (multiple statements on the same line) are generally discouraged

2023-11-15 09:41 UTC, ClasherKasten commented
> The problem now is that the others have to review code that already was reviewed.

Not really a problem. Your course can have special standards which could invalidate/complement the review.

2023-11-15 11:20 UTC, LeMixer commented
> > The problem now is that the others have to review code that already was reviewed.
> 
> Not really a problem. Your course can have special standards which could invalidate/complement the review.
> 
> 

Yes, it is a problem. The weekly reviews a part of our graded weekly tasks. This repo is meant to be a platform for our class to practice writing and reviewing Python code. Therefore it's not your business with whatever argumentation to leave reviews potentially disallowing us from writing a thorough review on this pull request. So please refrain from writing reviews in this repo in the future!

2023-11-15 13:54 UTC, GeFritz commented
> Almost good type annotations but types inheriting from `Generic` should have concrete types.

what exactly should i change?

2023-11-21 08:28 UTC, Reisii approved these changes
Nice work. Code works as intended and nice use of classes. Imo type annotations aren't necessary, so no reason for it to be a reason to request changes.

2023-11-24 11:34 UTC, merged