Loesung_06 Jan Merz (1778099, 1623571)
dhbw-ma-ppp/ppp-2023 pull request #150
Opened 2023-11-16 09:03 UTC by TrueEsel

task 1: 1778099
task 2: 1623571

2023-11-17 13:54 UTC, DrKeks1010 requested changes
Great solution overall. But you missed a small part of the assignment.

2023-11-17 13:54 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_06.py
> +# be identified by their full path. For the example above:
Sadly, you didn't write a function compliting this task. You did although write code to produce the required dictionary. You should therefor move the code in a seperate funcion, which will require the console session as an input parameter. Overall this should be a quick fix, as you already wrote all the necessary code.

2023-11-17 13:54 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_06.py
> +        return directory_dictionary
-- not mandatory --
returning the directory is unnecessary as the change of properties of objects in a dictionary will be done in place. So you might remove this line to improve readability.

2023-11-17 13:54 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_06.py
> +                    directory_dictionary = directory_dictionary[old_path].add_content(directory_dictionary, path)
-- not mandatory --
with the change suggestet above, you should also then remove the assignment here

2023-11-17 13:54 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_06.py
> +                directory_dictionary = directory_dictionary[path].add_content(directory_dictionary, file_name, file_size)
-- not mandatory --
with the change suggestet above, you should also then remove the assignment here

2023-11-17 18:56 UTC, TrueEsel commented on Exercises/JanMerz/exercises_06.py
> +# be identified by their full path. For the example above:
solved this problem by making build_directory return the necessary dicitonary

2023-11-17 18:56 UTC, TrueEsel commented on Exercises/JanMerz/exercises_06.py
> +        return directory_dictionary
removed return

2023-11-17 18:57 UTC, TrueEsel commented on Exercises/JanMerz/exercises_06.py
> +                    directory_dictionary = directory_dictionary[old_path].add_content(directory_dictionary, path)
removed assignment

2023-11-17 18:57 UTC, TrueEsel commented on Exercises/JanMerz/exercises_06.py
> +                directory_dictionary = directory_dictionary[path].add_content(directory_dictionary, file_name, file_size)
removed assignment

2023-11-22 08:04 UTC, DrKeks1010 approved these changes
Great Job

2023-11-22 14:58 UTC, CorvinAn97 commented
Overall a great Solution

2023-11-25 12:11 UTC, merged