Aufgaben zu Woche 06 (1778099;1623571)
dhbw-ma-ppp/ppp-2023 pull request #155
Opened 2023-11-16 18:44 UTC by TomKnoden

2023-11-22 16:13 UTC, paulseidel08 requested changes
Your code seems functional and efficient to me. Good job!
However, I have to request changes, because your file import doesn't work for everyone. Please use PathLib for that.

2023-11-22 16:13 UTC, paulseidel08 commented on Exercises/Tom_Knoden/Aufgaben_Woche_06.py
> +    console_session_file = 'data/terminal_record.txt'
Please use PathLib for importing the input file, so your code works for reviewers. You can just copy the file-importation from someone else, and edit the file name there.

2023-11-28 22:25 UTC, TomKnoden commented
I accidentaly resolved the conversation regarding your last change request...I hope that does not cause any further problems.
Nonetheless, I think I've also already adressed your change request regarding the use of PathLib in my code.
Is the PR ready to merge, or are there any unsolved problems left?

2023-11-29 06:38 UTC, paulseidel08 approved these changes
Good idea, to just ask the User for the file-path just via input()! 
Everything seems fine now.

2023-11-29 09:30 UTC, merged