Jasmin_Steid_Jan_Merz_Unfinished_Exercise_07
dhbw-ma-ppp/ppp-2023 pull request #162
Opened 2023-11-19 09:01 UTC by TrueEsel

This code was pair programmed by Jasmin Steidl and Jan Merz.
While the first part of the task is working fine, the second task is not working how its supposed to and we cant find the Error.
The way the code is written right now the program works for two frames and is then exited because of opcode 99. 
In these two frames the ball is moving towards the lower right part of the window and the paddle is moving in the same direction.
If the input_getter function is returning zero from the start (meaning the paddle is not moving at all) the ball is going up and breaking a block first, instead of going straight down.
We couldnt find out why this is the case.

Picture required by task 1:
![start](https://github.com/dhbw-ma-ppp/ppp-2023/assets/26006982/26142473-4949-4fc8-a344-48ec45c5a547)

2023-11-20 19:15 UTC, atrejut commented
- as far as I can tell you call `move_paddle` every time you got three value from the computer -- even if that particular set of values was not related to ball- or paddle-position at all...
- within `move_paddle` you /think/ you got a `ball_coordinate` as argument, but really what you pass is just the last value you got from the int-computer? which actually is a tile type I think, and not a position of anything at all?
- and this leads to you making the wrong move: the first time you are asked to provide an input the real x-coordinates are pad=21, ball=19, so you should be going left -- but you decide to go right, probably just because the last input to `move_paddle` happened to make you go right accidentally.

**general advice**:
you are trying to do something with the computers output every time you receive a new value. I would recommend just storing the value you get at that point, because you don't actually need to parse it until you are asked to provide a direction. at that point, go through all the stored outputs, figure out where ball and paddle are, and go the right direction...

2023-11-27 18:40 UTC, DrKeks1010 requested changes
Overall a great solution.
Still minor tweaks are required (first two comments), shouldn't take more than 5 minutes, as your solution works overall and is a great solution. 

Other changes aren't required, but will help with code style, readability and consistency.

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +root_dir = pathlib.Path().absolute().parents[1]
Change this to:
root_dir = pathlib.Path(__file__).absolute().parents[2]

This way, the code will use this file as an anchor when searching for breakout_commands. This way, everybody can execute this file and it doesnt matter, where they execute it from

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +picture_pixels = []
unnecessary assignment, please remove

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +
Not Mandatory: (improved readability and code structure)

you might want to consider splitting this method into two:
one that fetches all the inputs and stores them (might add into deque with size limit of 3)
And another one, that will read all 3 bits of data, once all have been collected. This way this method will be much easier to read. This will have the added benefit of you not having to store the x_coordinate, y_coordinate, zaehler, relevant_tiles and ignore_value. As you will always have all 3 required values when entering this method.

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +    zaehler = 0
Not Mandatory: (code consistency)

Change zaehler to counter / change everything into german

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +        if (computer_return == -1 or self.ignore_value):
Not Mandatory: (code style)

brackets aren't required and thus should be removed

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +            if(self.zaehler == 0 and not self.painted_main_screen):
Same as above

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +            if(self.zaehler < 3):
Same as above

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +            elif(self.zaehler == 3):
Same as above

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +                if(computer_return == 4):
Same as above

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +                    if(self.painted_main_screen):
Same here

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +            if(self.matrix[21, index] == 3):
And here

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +        if(paddle_coordinate < self.ball_coordinate):
And here

2023-11-27 18:40 UTC, DrKeks1010 commented on Exercises/JanMerz/exercises_07.py
> +        elif(paddle_coordinate > self.ball_coordinate):
And here a last time

2023-11-28 08:57 UTC, TrueEsel commented on Exercises/JanMerz/exercises_07.py
> +
while I do see your point and believe that you're right, I do not have the time to make this change this week

2023-11-29 16:48 UTC, DrKeks1010 approved these changes
All problems fixed. Great Solution

2023-11-29 16:50 UTC, merged