Paul seidel exercise06 (1778099,X)
dhbw-ma-ppp/ppp-2023 pull request #164
Opened 2023-11-20 17:03 UTC by paulseidel08

Finally finished part1. Unfortunately, I spent so much time on debugging, I coudn't make part2. Hours spent: about 7h

But part1 should behave like it's supposted to.

2023-11-21 08:35 UTC, fabischw commented on Exercises/PaulSeidel/PSeidel_exercises_06.py
> +with open("./data/terminal_record.txt", "r") as input_file:
While I like the fact that you're trying to isolate the file into a data directory, the code in it's current state won't run unless I manipulate the source code or create a directory called data in your working directory and copying the record over from the main/data directory. Consider using relative paths or using a library like pathlib to just read the file from (relative path): ```./../../data/terminal_record.txt ``` .

2023-11-21 22:41 UTC, thecodingcube77 requested changes
You don't make it easy for yourself.

2023-11-21 22:41 UTC, thecodingcube77 commented on Exercises/PaulSeidel/PSeidel_exercises_06.py
> +            folder_structure[current_path + name_of_new_dir] = []    #adding the dir to the dict with an empty list as value and the full path-list as string as key.
`collections.defaultdict` can save you this initialization with an empty list.

2023-11-21 22:41 UTC, thecodingcube77 commented on Exercises/PaulSeidel/PSeidel_exercises_06.py
> +            folder_structure[current_path] = temp
saving individual file names and sizes is not really needed in this task as you only need the sizes of whole directories but could maybe be useful sometime.

2023-11-21 22:41 UTC, thecodingcube77 commented on Exercises/PaulSeidel/PSeidel_exercises_06.py
> +def recursive_calculate_size(current_directory = ("/",)):
This whole function could be done inside the function above by adding the adding the size of a currently encountered file to the current as well as all upstream directories. This would save a bit of work in my opinion.
Could be done like this:
```py
if current_line_has_file:                             # if the element currently listed is a file
    for path in cwd_and_upstream_paths(current_path): # loop through all parent paths from the current directory to the root directory
        dir_sizes_dict[path] += current_file_size     # add the size of the currently listed file to the directory
```
This would be done in the last `else` in the `create_folder_structure()` function.
I would create a generator for `cwd_and_upstream_paths()`  which takes the `current_dir` as an argument. Using `pathlib` for the `current_dir` makes the creation of the generator really easy.

2023-11-21 22:41 UTC, thecodingcube77 commented on Exercises/PaulSeidel/PSeidel_exercises_06.py
> +            dir_sizes[current_directory] = temp
This being so complicated is due to you creating a very complicated system to store your data.

2023-11-21 22:41 UTC, thecodingcube77 commented on Exercises/PaulSeidel/PSeidel_exercises_06.py
> +    return sum
You could just write
```py
return sum([dir_size for dir_size in dictionary.values() if dir_size <= 100000])
```

2023-11-21 22:41 UTC, thecodingcube77 commented on Exercises/PaulSeidel/PSeidel_exercises_06.py
> +def sum_dirs_of_criteria(dictionary: dict):
I would not name it dictionary. What information does the dictionary hold?  I don't know from reading this.

2023-11-21 22:41 UTC, thecodingcube77 commented on Exercises/PaulSeidel/PSeidel_exercises_06.py
> +    for dir_name in dictionary:
You can just loop over the values of a dict by using `for value in dictionary.values()`

2023-11-21 22:41 UTC, thecodingcube77 commented on Exercises/PaulSeidel/PSeidel_exercises_06.py
> +###############################################################################
Quick suggestion for part 2:
```py
def find_dir_to_delete(needed_size: int, file_system_size: int, file_sizes_dict: dict):
    # calculate the space you need to free
    size_of_dir_to_delete = min(dir_size for dir_size in dir_sizes_dict.values() if dir_size >= needed_space) # find the smallest dir size which would free up enough space
    index_of_dir = list(dir_sizes_dict.values()).index(size_of_dir_to_delete) # find the index of the determined directory by the determined size
    path_of_dir_to_delete = list(dir_sizes_dict.keys())[index_of_dir]         # get the key(=path) from the list of keys as the index from the values directly translates to the keys
    return path_of_dir_to_delete
```
I have to note that this way of interacting with a dict is really inefficient as a dict is not made to be used the other way around.

2023-11-21 22:41 UTC, thecodingcube77 commented on Exercises/PaulSeidel/PSeidel_exercises_06.py
> +print(sum_dirs_of_criteria(run_and_return_dict()))
You should save the `dir_dict` in a variable to reuse it in task 2 (if you decide to do it).

2023-11-21 22:45 UTC, thecodingcube77 commented
Also, when creating new branches:
first: `git checkout main`
second: `git pull`
third: `git checkout -b new_branch_name`

2023-11-23 09:22 UTC, fabischw approved these changes
Path problems were fixed. Approving this as you stated you do not want to spend any more time on the assignement.

2023-11-23 12:46 UTC, thecodingcube77 approved these changes
I'll approve as well due to the time you already spent on the exercise.

2023-11-23 14:48 UTC, fabischw commented
If you want to merge the code in it's current state, I recommend adding a docstring at the top of the python document explaining why it's not finished and what exactly is not finished to avoid future confusion

2023-11-29 09:35 UTC, merged