Julius Dralle Task 7. No High-Score made yet
dhbw-ma-ppp/ppp-2023 pull request #165
Opened 2023-11-22 08:03 UTC by RubelOS

It is working.
![PicturePart1](https://github.com/dhbw-ma-ppp/ppp-2023/assets/35865838/8ee1e58f-d178-476a-b5af-0d5be9b99735)

2023-11-22 09:58 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_07.py
> +    input_lines_int = None
```py
del input_lines_int
```
Will remove the variable and free it's space.
To just create one list you could just
```py
input_lines = [int(x) for x in input_file.read().splitlines()]
```
Should do exactly the same.

2023-11-22 10:06 UTC, fabischw requested changes
Please remove the data directory or revert the file to it's original state. In the current PR, you change the breakout_commands.txt file. You can either just remove this in the PR or write wrapper function for both exercises with the second one replacing the value at index 0 so the original file is preserved in it's original state.

2023-11-22 10:22 UTC, fabischw approved these changes
Problem was adressed. You might want to consider adding a requirements.txt so users and reviewers can easily view and install dependencies. This is optional for now in my opinion as every student of the class should now have numpy and matplotlib installed.

2024-01-27 18:54 UTC, fabischw commented
I will be merging this PR if it does not get merged by the PR creator within the next 3 days in an effort to clean up the repo (More information can be found in [Issue #228](https://github.com/dhbw-ma-ppp/ppp-2023/issues/228))

2024-01-31 03:11 UTC, merged