(not working) Celina 7
dhbw-ma-ppp/ppp-2023 pull request #177
Opened 2023-11-23 21:06 UTC by CelinaRiegel

Part 1 isnt working yet. I spend way to many hours on this. Maybe I have time to finish it on the weekend.

2023-11-23 23:40 UTC, TomKnoden commented
Try to reduce the use of global variables in your code. Instead, consider passing variables as parameters to functions.
For example in line 56 and 57.

2023-11-24 00:47 UTC, christianrietzsch requested changes
the game is now working
i would recommend using `return int(input())` in line 86 to play the game manually
to make a screenshot for task 1, because the last minute of the computer playing 
uses a lot of resources
(i did not play it to the end with graphical output enabled, but tested with graphical output disabled that the game works!)

2023-11-24 00:47 UTC, christianrietzsch commented on Exercises/Celina/exercises_07.py
> +with open("breakout_commands.txt", "r") as data:
you should use `../../data/breakout_commands.txt` as the path
if you want to directly jump to the game with inputs
(which you should, since you have the graphical output function in the input collector)
add `commands[0] = 2` after `commands.append()`

2023-11-24 00:47 UTC, christianrietzsch commented on Exercises/Celina/exercises_07.py
> +    global ball_pos
no global variables needed

2023-11-24 00:47 UTC, christianrietzsch commented on Exercises/Celina/exercises_07.py
> +    tiles[x,y]=types
you need to switch `x` and `y` to match the axis with the game: `tiles[y,x]`
you also have to check for types that have other values than 1,2,3,4 because you do not filter
the output for highscore-values: `= types if types in [1,2,3,4] else 0`

2023-11-24 00:47 UTC, christianrietzsch commented on Exercises/Celina/exercises_07.py
> +        x = output[element]
you are using the element as an index

2023-11-24 00:47 UTC, christianrietzsch commented on Exercises/Celina/exercises_07.py
> +        element+=3
you are incrementing the respective element of output and not the index
(not needed if you change your code to the for loop in my comment)

2023-11-24 00:47 UTC, christianrietzsch commented on Exercises/Celina/exercises_07.py
> +    for element in output:
use `for index in range(len(output))[::3]:`
instead and replace element with index

2023-11-24 00:47 UTC, christianrietzsch commented on Exercises/Celina/exercises_07.py
> +breakout()
not needed if you change directly to the game (task 2)

2023-11-24 00:47 UTC, christianrietzsch commented on Exercises/Celina/exercises_07.py
> +    global output
global variable not needed

2023-11-24 00:47 UTC, christianrietzsch commented on Exercises/Celina/exercises_07.py
> +    fig, ax = plt.subplots()
not needed: just use `plt.imshow()`
before you refresh the screen you could clear it with `plt.cla()`

2023-11-24 00:47 UTC, christianrietzsch commented on Exercises/Celina/exercises_07.py
> +    plt.show()
this makes the screen static
use `plt.show(block=False)` and `plt.pause(0.0001)` instead

2023-12-28 15:04 UTC, christianrietzsch approved these changes
LGTM

2024-01-27 18:54 UTC, fabischw commented
I will be merging this PR if it does not get merged by the PR creator within the next 3 days in an effort to clean up the repo (More information can be found in [Issue #228](https://github.com/dhbw-ma-ppp/ppp-2023/issues/228))

2024-01-31 03:10 UTC, merged