Robert Walz Woche07
dhbw-ma-ppp/ppp-2023 pull request #179
Opened 2023-11-23 22:35 UTC by LeMixer

I extended my own computer to support the new features and partnered up for task 1 and 2 with @fabischw

2023-11-28 14:56 UTC, FelixRegnier requested changes
Insgesamt solide Loesung. Bitte noch wie in Zeile 30 und 44 geschrieben, das Bild aus Aufgabe 1 und den Highscore aus Aufgabe 2 in der PR hinzufuegen

2023-11-28 14:56 UTC, FelixRegnier commented on Exercises/RobertWalz/exercises_07/computer.py
> +        return 0
Der Computer sieht soweit gut aus. Manche docstrings von den ersten Funktionen haben noch Rechtschreibfehler oder doppelte Wörter.

2023-11-28 14:56 UTC, FelixRegnier commented on Exercises/RobertWalz/exercises_07/main.py
> +            self.triplet_arr = []
An dieser Stelle haette ich mit range gearbeitet mit step_size = 3. Allerdings ist deine Loesung auch in Ordnung und funktioniert

2023-11-28 14:56 UTC, FelixRegnier commented on Exercises/RobertWalz/exercises_07/main.py
> +        key = key.key_code
Zeile 169 wird meiner Meinung nach etwas unuebersichtlich. Vielleicht waeren 2 Variablen eine etwas bessere Loesung.

2023-12-13 16:33 UTC, fabischw approved these changes
Requested changes were implemented. Dismissing old CR as a requested review was not delivered and the requested changes are not high enough in severity to justify waiting any longer for a merge.

2023-12-13 16:33 UTC, merged