Aufgaben 1 update
dhbw-ma-ppp/ppp-2023 pull request #28
Opened 2023-10-13 06:27 UTC by not-too-deranged

2023-10-13 08:28 UTC, thecodingcube77 requested changes
Bitte ändere die Lösung zur Aufgabe in Z. 31 und die Ausgabe der Ergebnisse.

2023-10-13 08:28 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung1.py
> +print(x%y)
Schreib das Ergebnis am besten in einen string, der angibt was die Werte bedeuten, die du ausgibst.
Z.B. mit einem f-string wie folgt:
```
print(f'Der Quotient der Division: {x / y}\nDer Rest der Division: {x % y}')
```
In einen f-string kannst du einfach ein paar geschweifte Klammern schreiben und die Variable in den Klammern wird in einen String umgewandelt und für die geschweiften klammern in den String eingefügt.

Außerdem soll das jeweilige mit nur einem print() ausgegeben werden.

2023-10-13 08:28 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung1.py
> +print (res)
Verschachtelte for-Schleifen sind in diesem Fall nicht nötig und unnötig kompliziert.
Du solltest lieber ein set mit union() verwenden oder zwei sets mit & verküpfen:
```
res = set(first_list).union(set(second_list))
# oder
res = set(first_list) & set(second_list)
```

2023-10-13 08:28 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung1.py
> +print(listb.count("a"))
Sehr gut die Listen zu joinen

2023-10-14 11:50 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung1.py
> +res = set(first_list) & set(second_list)
Top jetzt musst du nur noch das print-statement für die Frage "which and how many elements are common to the two lists above?" machen

2023-10-17 13:00 UTC, fabischw approved these changes
Requested changes were successfully implemented.

2023-10-17 13:03 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung1.py
> +print (res)
Die Aufgabe fordert auch die Ausgabe der Menge der Elemente die in beiden Listen vorkommen

2023-10-19 08:05 UTC, merged