Celina
dhbw-ma-ppp/ppp-2023 pull request #32
Opened 2023-10-13 08:58 UTC by CelinaRiegel

exercise_1.beendet

2023-10-13 09:25 UTC, RubelOS requested changes
Pls remove the empty file.

The whole thing looks perfect! 👌👌🥰🥰🥰😶‍🌫️😶‍🌫️😶‍🌫️🫡🫡🫡🫡🤡👽

2023-10-13 09:25 UTC, RubelOS commented on Exercises/CelinaRiegel/first_test.py
Should be removed

2023-10-13 09:25 UTC, RubelOS commented on Exercises/CelinaRiegel/exercise_01.py
> +print("remainder=", 2711274328912%23369245575)
looks good! Keep an eye on the task "single print()"
you can use `print(solution1 \n solution2)`!!!

2023-10-13 09:25 UTC, RubelOS commented on Exercises/CelinaRiegel/exercise_01.py
> +print(gleich, "elements are the same")
keep in mind that u can use Pytohn's integrated functions. Your solution may be inefficient but still good!

2023-10-13 09:25 UTC, RubelOS commented on Exercises/CelinaRiegel/exercise_01.py
> +    anzahl+=i.count("a")
same as before. Still good! love it!

2023-10-19 07:51 UTC, RubelOS commented
Why did u delete your exercise_01.py too?

2023-10-19 09:25 UTC, RubelOS approved these changes
good solution

2023-10-19 09:25 UTC, RubelOS commented on Exercises/Celina/exercise_01.py
> +print(gleich, "elements are the same")
next time you can use inbuilt functions like len() of the intersect of both lists. For being able to use intersect() u have to convert both lists to a set

2023-10-24 18:16 UTC, atrejut commented
@CelinaRiegel feel free to merge this :)

2023-10-25 14:43 UTC, merged