Paul´s exercise02
dhbw-ma-ppp/ppp-2023 pull request #33
Opened 2023-10-13 17:04 UTC by paulseidel08

Should be ready for being reviewed.

2023-10-13 19:54 UTC, RubelOS requested changes
- Multiple exercises in one Branch
- Some little problems in exercise 1

**All in all pretty good! well done!**

2023-10-13 19:54 UTC, RubelOS commented on Exercises/20231006-PaulSeidelExercises01.py
U were supposed to put ur exercise in another folder called "PaulSeidel"

2023-10-13 19:54 UTC, RubelOS commented on Exercises/20231006-PaulSeidelExercises01.py
> +for i in range(0,l2):
You could use len(first_list) directly in the range() but you could also use Python's unbuilt functions(count) for more efficiency.
You were also meant to print the a's of both lists seperately.

2023-10-13 19:54 UTC, RubelOS commented on Exercises/exercises_02.py
U are meant to open a new Branch for the second task

2023-10-14 06:25 UTC, atrejut commented
In addition to what @RubelOS said, you're also changing the template file for the exercise (`Exercises/exercise_02.py`) rather than modifying you own copy

2023-10-15 14:58 UTC, thecodingcube77 commented on Exercises/exercises_02.py
> +# As an example, if the list of integers passed to your function is
This line states, that you should pass an array of integers to your function, which you don't do. This is minor but should fix this, so you could reuse your function for other arrays.

2023-10-15 15:08 UTC, thecodingcube77 commented on Exercises/exercises_02.py
> +print(computerSim()) #execute the function and print the return statement
Please only print the first element of the returned list. This can be achieved by only returning the first element of the list as required

2023-10-17 12:49 UTC, closed without merging