Felix Regnier 01
dhbw-ma-ppp/ppp-2023 pull request #35
Opened 2023-10-14 13:15 UTC by FelixRegnier

2023-10-15 18:19 UTC, FritzRa commented on Exercises/Felix Regnier/ex01_Felix_Regnier.py
> +print("quotient: " + str(a/b) + ", remainder: " + str(a%b))
Eine weiter mögliche Schreibweise wäre:
`print("quotient: " , a/b , ", remainder: " , a%b)`
könntest du bei vielen der Print ausgaben machen, dann müsstest du nicht immer str(...) schreiben.

Sonst ist der Code gut.

2023-10-18 13:17 UTC, christianrietzsch commented on Exercises/Felix Regnier/ex01_Felix_Regnier.py
> +print("quotient: " + str(a/b) + ", remainder: " + str(a%b))
you could use `a//b` instead of `a/b` for integer instead of floating point division

2023-10-19 08:22 UTC, UtkuDHBW commented on Exercises/Felix Regnier/ex01_Felix_Regnier.py
> +      e.append(first_list[i])
Man kann statt die For-Schleife auch die Liste zu einen Set Datentyp wechseln und die intersection Methode verwenden, die speziell für die Suche nach gemeinsamen Elementen geeignet ist.

2023-11-02 09:28 UTC, FritzRa requested changes
see reviews from before

2023-11-18 09:11 UTC, atrejut commented
@FelixRegnier please try to get this old PR merged -- take a look at the reviews, things should be easy enough to fix now.

2023-11-30 14:02 UTC, closed without merging