Solution to Task 2 Julius Dralle
dhbw-ma-ppp/ppp-2023 pull request #36
Opened 2023-10-14 23:00 UTC by RubelOS

2023-10-15 14:52 UTC, thecodingcube77 requested changes
Please make it work like required as stated in ma comments. You can look at my solution or ask me if you have further questions.

2023-10-15 14:52 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_02.py
> +        else:
You don't cover all cases. What if the given argument is no number but also not a single character?

2023-10-15 14:52 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_02.py
> +def calculatorMachine( memoryList, *args):
Your whole calculatorMachine() is not working as required in the task, because you never mutate the memoryList passed into the function. This is needed for you to get the right solution.
This idea is also quite overcomplicated, you should not really need a second function.

2023-10-15 14:52 UTC, thecodingcube77 commented on Exercises/JuliusDralle/exercises_02.py
> +print(splittingMachine(*["1","a","b","5","6"]))
You dont't cover all cases in your tests. You should pass a string consisting out of numbers and letters into the splittingMachine() function.
E.g.: "34sdfKHkls" which should then be completely filtered out.

2023-10-15 17:47 UTC, thecodingcube77 approved these changes
Now it's all correct

2023-10-18 14:34 UTC, DrKeks1010 approved these changes
Well done

2023-10-19 09:41 UTC, fabischw requested changes
There are a few small issues as highlighted in my comments.
You may also want to consider to add docstrings to your functions.

2023-10-19 09:41 UTC, fabischw commented on Exercises/JuliusDralle/exercises_02.py
> +def calculate():
Your function for exercise one does not take an array as an input as stated in the instructions and instead uses the commands defined above. Please change your function to take an input as stated in the requirements.

2023-10-19 09:41 UTC, fabischw commented on Exercises/JuliusDralle/exercises_02.py
> +        elif len(i) == 1 :
Your solution to exercise two adds strings to the charList OR to the numberList. Input "1" is only added to the numberList, not to the string list. The requirements state that the numberList should contain ALL values that can be interpreted as a number and the charList should contain ALL values that are strings of length 1. "1" should therefore end up in both arrays.

2023-10-20 07:23 UTC, fabischw approved these changes
requested changes were implemented; looks good. Consider using a different iterator variable next time if it is clear what the objects you are iterating over are - in this example elements or inpt_strings etc. .

2023-10-25 15:43 UTC, merged