added task 2
dhbw-ma-ppp/ppp-2023 pull request #40
Opened 2023-10-16 13:29 UTC by paulseidel08

2023-10-17 12:18 UTC, DrKeks1010 requested changes

2023-10-17 12:18 UTC, DrKeks1010 commented on Exercises/PaulSeidel/P.Seidel_exercises_02.py
> +                sum = (listCS[counter+1] + listCS[counter+2])
The value at "listCS[counter+1]" should be interpreted as the id of the cell you have to add (or multiply)

Use listCS[listCS[counter+1]] instead.

2023-10-17 12:18 UTC, DrKeks1010 commented on Exercises/PaulSeidel/P.Seidel_exercises_02.py
> +        if temp.isdigit():  #checks if the string is made out of numbers from 0 to 9
Note: this will only work on integers.
To also accept inputs like '2.5', try using a try-except block

2023-10-17 12:18 UTC, DrKeks1010 commented on Exercises/PaulSeidel/P.Seidel_exercises_02.py
> +    list = collector()
Great idea to fetch the method inputs on runtime.
Sadly using this approach you dont have 3 fixed test cases as required by the task.

You may add 3 pre determined arrays, which you can use to swap the 'collector()' with

2023-10-17 13:00 UTC, paulseidel08 commented on Exercises/PaulSeidel/P.Seidel_exercises_02.py
> +        if temp.isdigit():  #checks if the string is made out of numbers from 0 to 9
I didn't consider allowing floats, because the exercise wasn't clear with that. I interpreted it like that:
numbers: integers
decimal numbers: floats

2023-10-20 09:19 UTC, DrKeks1010 approved these changes
Looks great

2023-11-03 08:56 UTC, merged