Jasmin02
dhbw-ma-ppp/ppp-2023 pull request #43
Opened 2023-10-16 15:25 UTC by not-too-deranged

2023-10-17 11:19 UTC, paulseidel08 commented on Exercises/JasminSteidl/Übung2.py
> +# Write a function that takes as input a list of integers and returns a single integer number.
We were supposed to put the second task in a new branch and not in the same branch as the first.

2023-10-17 11:26 UTC, paulseidel08 commented on Exercises/JasminSteidl/Übung2.py
> +def function(*args):
better use a function-name that describes what the function does. This is part of comprehensive code.

2023-10-17 11:26 UTC, paulseidel08 commented on Exercises/JasminSteidl/Übung2.py
> +def function(*args):
Same for the variables

2023-10-17 11:27 UTC, paulseidel08 commented on Exercises/JasminSteidl/Übung2.py
> +        if arg.isdigit () or (arg[0]=="-" and arg[1:].isdigit()): #for negative numbers, floats
depending on the way you interpret the task, that's a very good idea to filter also floats and negative numbers!

2023-10-17 11:36 UTC, paulseidel08 commented on Exercises/JasminSteidl/Übung2.py
> +        if arg.isdigit () or (arg[0]=="-" and arg[1:].isdigit()): #for negative numbers, floats
correction: you enable negative numbers, but no floats. Or am I wrong with that? I'm not completely sure.

2023-10-17 11:41 UTC, paulseidel08 reviewed
All in all a very good code. But you shouldn't upload multiple exercises into one file.

2023-10-20 11:14 UTC, thecodingcube77 requested changes
Your check for numbers should be changed so that it is more consistent

2023-10-20 11:14 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung2.py
> +            or (arg[0]=="-" and arg[1].isdigit() and arg[2]=="." and arg[3:].isdigit()): #for negative numbers and floats
This is a very unreadable if statement. What you are trying to do here is to filter out floats, but you can only filter out numbers with a floating point at the index 1 and no other. So you would not filter out the number `1234.5678`, because it does not fall under any part of your if statement.
I would suggest a cast to float, which is way easier to read and understand. But be aware that a cast to float will throw an error if you give it something that can not e cast to a float.

2023-10-20 11:14 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung2.py
> +    modInput=input.copy() #input copy not to f with original
It is not necessary to copy the array because you don't need it for anything else in this case

2023-10-20 11:14 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung2.py
> +            pointer+=4
The variables make the code very understandable and easy to follow.

2023-10-20 11:14 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung2.py
> +            pointer+=4
The addition of 4 at the end of both if's  can be done at the end of the for loop so you only have to write this line once. It also helps to prevent bugs in a larger scale. If you want to change the 4 to a 6 for example, you would have to do it twice in your solution, of which you can forget it once. If you only have one place to change the value you cannot have them out of sync.

2023-10-20 12:30 UTC, thecodingcube77 requested changes
You should take a look at the naming conventions in python.
You also have to test your function in task 2 where you filter the arguments.

2023-10-20 12:30 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung2.py
>  result=stringFunction(*example)
You do not test your function with 3 examples

2023-10-20 12:30 UTC, thecodingcube77 commented on Exercises/JasminSteidl/Übung2.py
> +def simComputer (Input):
Variable names are always lower case

2023-10-22 14:12 UTC, thecodingcube77 approved these changes
The requested changes got implemented. I don't see any more problems.

2023-10-25 10:37 UTC, TomKnoden commented
Everything in your program seems to be working after fixing the issues that were adressed. Well done!

2023-10-25 15:46 UTC, merged