solution for exercise 2
dhbw-ma-ppp/ppp-2023 pull request #44
Opened 2023-10-17 11:31 UTC by christianrietzsch

2023-10-17 11:59 UTC, DrKeks1010 approved these changes
Overall a great solution.

Be will find out tomorrow, if singel digits like '2' should also be interpreted as strings with just one character or if the program should exit after parsing '2' to a number, so you might need to adjust this.

2023-10-17 11:59 UTC, DrKeks1010 commented on Exercises/ChristianRietzsch/exercises_02.py
> +                print("Error, Illegal Instruction: {memory[current]}")
This should be an f string, i suppose

2023-10-17 12:56 UTC, GeFritz commented on Exercises/ChristianRietzsch/exercises_02.py
> +                print("Error, Illegal Instruction: {memory[current]}")
bro lass mal paar reviews übrig

2023-10-17 12:59 UTC, fabischw requested changes
Task 2 does not accept the input "1" as both char and number. It only adds the "1" to the number list, not to the char list.

2023-10-18 11:18 UTC, fabischw approved these changes
problem has been solved and requested changes implemented. well done.

2023-10-25 15:45 UTC, merged