Philipp Kirschke week 2
dhbw-ma-ppp/ppp-2023 pull request #48
Opened 2023-10-18 14:08 UTC by The-Linux-User

2023-10-18 14:17 UTC, CorvinAn97 commented
it was a good idea to consider the hex numbers! :)

2023-10-19 14:38 UTC, s231365 requested changes
Overall your solution does what it should, but i don't understand how you check if the inputs are numbers (exercise 2). I only see the check for Hex numbers.

2023-10-19 14:38 UTC, s231365 commented on Exercises/Philipp Kirschke/exercises_02.py
> +        if commands[i] == 1:
maybe consider using variables, it makes the code easier to read as well as some comments

2023-10-19 14:38 UTC, s231365 commented on Exercises/Philipp Kirschke/exercises_02.py
> +def checkHex(s):
please use a different name for the variable. with s it is not clear what you mean

2023-10-19 14:38 UTC, s231365 commented on Exercises/Philipp Kirschke/exercises_02.py
> +while i < len(inputList):
same here, use a different name for the variable. i is not meaningful

2023-10-19 14:45 UTC, The-Linux-User commented
> Overall your solution does what it should, but i don't understand how you check if the inputs are numbers (exercise 2). I only see the check for Hex numbers.

I split all strings in their individual chars. I then check every char if it is a valid hex number (so 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, A, B, C, D, E, F) Non-hex numbers are of course included in the regular numbers from 0-9, so they pass as well. If all chars match the criteria above, the whole number will be added to the number list

2023-10-19 14:46 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_02.py
> +        if commands[i] == 1:
I wrote all of this before he told us on Wednesday not to use i, ... for variables. Will change it later

2023-10-20 06:42 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_02.py
> +        if commands[i] == 1:
Has been changed to index

2023-10-20 06:42 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_02.py
> +def checkHex(s):
Has been changed to string

2023-10-20 06:42 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_02.py
> +while i < len(inputList):
Has been changed to index

2023-10-20 06:43 UTC, s231365 approved these changes

2023-10-26 07:11 UTC, merged