Aufgabe 02 Jan Merz
dhbw-ma-ppp/ppp-2023 pull request #53
Opened 2023-10-18 17:51 UTC by TrueEsel

2023-10-18 21:00 UTC, christianrietzsch requested changes
please add the required return value in task 2

2023-10-18 21:00 UTC, christianrietzsch commented on Exercises/Jan Merz/exercises_02.py
> +    print(numberList, " are numbers and ", charList, " are single characters")
the function should return two lists: `return (numberList, charList)`

2023-10-18 21:00 UTC, christianrietzsch commented on Exercises/Jan Merz/exercises_02.py
> +    for i in range(len(args)):
you should just directly loop through the elements of args: `for element in args:` if you never use the index
except to reference an element: `args[i]` -> `element`

2023-10-18 21:00 UTC, christianrietzsch commented on Exercises/Jan Merz/exercises_02.py
> +def computer_sim(arr):
good solution

2023-10-18 21:00 UTC, christianrietzsch commented on Exercises/Jan Merz/exercises_02.py
> +splitArgs("0", "-4254", "0.00000000001", "ä", "pß", "?")
nice test cases including negative numbers, floats and complex (imaginary) numbers

2023-10-18 21:22 UTC, TrueEsel commented on Exercises/Jan Merz/exercises_02.py
> +    print(numberList, " are numbers and ", charList, " are single characters")
fixed that

2023-10-19 06:32 UTC, christianrietzsch approved these changes

2023-10-25 15:53 UTC, merged