This week's stuff
dhbw-ma-ppp/ppp-2023 pull request #54
Opened 2023-10-18 22:30 UTC by Reisii

Pls go easy on me

2023-10-19 13:56 UTC, fabischw requested changes
Job well done; a few things could've been implemented with reduced complexity as highlighted by my comments. You may also consider using docstrings next time.
Great solution overall, source code changes are not necessarily required.
However, your python file seems to be in the parent directory  of the repo instead of a personal folder in ./Exercises. This issue has to be resolved.

2023-10-19 13:56 UTC, fabischw commented on Tufgaben2.py
> +    for i in range(0, len(arr)):
Works here but just looping trough the array elements would have been easier and easier to understand.

2023-10-19 13:56 UTC, fabischw commented on Tufgaben2.py
> +            char_list.append(arr[i])
this solution works but using one if statement for the number matching and a second if case with same indentation for chars would have been easier.

2023-11-18 09:26 UTC, atrejut commented
@Reisii Please try to get this old PR merged...

2023-11-21 09:14 UTC, fabischw approved these changes
Problems were adressed.

2024-01-27 18:53 UTC, fabischw commented
I will be merging this PR if it does not get merged by the PR creator within the next 3 days in an effort to clean up the repo (More information can be found in [Issue #228](https://github.com/dhbw-ma-ppp/ppp-2023/issues/228))

2024-01-31 03:09 UTC, merged