Exercises Woche2
dhbw-ma-ppp/ppp-2023 pull request #56
Opened 2023-10-19 08:50 UTC by CelinaRiegel

2023-10-19 10:43 UTC, LeMixer requested changes

2023-10-19 10:43 UTC, LeMixer commented on Exercises/Celina/exercises_02.py
> +                sum=commands[first_pos] * commands[second_pos]
Misleading variable `sum` when multiplying numbers the result is not a sum, but rather a product.

2023-10-19 10:43 UTC, LeMixer commented on Exercises/Celina/exercises_02.py
> +                thierd_pos=commands[i+3]
typo

2023-10-19 10:43 UTC, LeMixer commented on Exercises/Celina/exercises_02.py
> +            if i != i:
This condition will never run since this is a contradiction.

2023-10-19 10:43 UTC, LeMixer commented on Exercises/Celina/exercises_02.py
> +    return number_list, not_number_list
The task is to sort values which can be interpreted as a number and 
>all strings which contain just one character

2023-10-20 06:28 UTC, CelinaRiegel commented on Exercises/Celina/exercises_02.py
> +            if i != i:
That was my solution to put nan in the not_number list.

2023-11-03 08:04 UTC, merged