Initial Commit: Exercise 03
dhbw-ma-ppp/ppp-2023 pull request #61
Opened 2023-10-20 08:07 UTC by RubelOS

2023-10-21 23:47 UTC, GeFritz commented
Wieso hast du ein pull request eröffnet obwohl du nicht fertig bist?

2023-10-22 05:50 UTC, RubelOS commented
True, hätte nur den Branch eröffnen können. War etwas voreiligAm 22.10.2023 01:47 schrieb Gerrit ***@***.***>:
Wieso hast du ein pull request eröffnet obwohl du nicht fertig bist?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-10-22 16:45 UTC, GeFritz requested changes
The code `2-Ace of diamonds ` seems to be a misunderstanding. Else nice and readable code. Answer to question three is wrong, lacks just one simple logic fix. Consider using assert functions to test your code.

2023-10-22 16:45 UTC, GeFritz commented on Exercises/JuliusDralle/exercises_03.py
> +# The Result to this is: 19
The answer to your snippet is 1992.

2023-10-22 16:45 UTC, GeFritz commented on Exercises/JuliusDralle/exercises_03.py
> +    for iterator_numbers in range(bound_lower, bound_higher+1):
The task states including lower bound and excluding upper bound.

2023-10-22 16:45 UTC, GeFritz commented on Exercises/JuliusDralle/exercises_03.py
> +                if number_string[iterator_charsInString - 1] == number_string[iterator_charsInString]:
There is a mistake in your code as you also count numbers in rows of three and higher. The task explicitly states an exact amount of two equal numbers. 
If we add `and number_string.count(number_string[iterator_charsInString])==2` in line 168, the answer is `1306 `which seems to be correct.

2023-10-22 16:45 UTC, GeFritz commented on Exercises/JuliusDralle/exercises_03.py
> +}
That is alot of work. But it looks nice, well done!

2023-10-22 16:45 UTC, GeFritz commented on Exercises/JuliusDralle/exercises_03.py
> +    "02" : "2",
In the task 2-Ace means in range 2 to ace, not 2-ace of diamonds.

2023-10-22 16:45 UTC, GeFritz commented on Exercises/JuliusDralle/exercises_03.py
> +        return(cardtype_dict[self.card_type], suits_dict[self.card_suite])
Nice solution to implement new card class. Using dict ids is also simple and clear. What if index is out of range?

2023-10-22 16:45 UTC, GeFritz commented on Exercises/JuliusDralle/exercises_03.py
> +    wanted_cards = ["07","08","09","10","11","12"]
The skat deck is missing the ace card for each suit. It should be 32 cards in total.

2023-10-22 16:56 UTC, GeFritz commented on Exercises/JuliusDralle/exercises_03.py
> +    "12" : "King"
There seems to be a key error here.

2023-10-23 08:02 UTC, RubelOS commented on Exercises/JuliusDralle/exercises_03.py
> +# The Result to this is: 19
Yes sorry, i did miss the last two chars. Thanks!

2023-10-23 08:02 UTC, RubelOS commented on Exercises/JuliusDralle/exercises_03.py
> +    for iterator_numbers in range(bound_lower, bound_higher+1):
I did not even notice. Thank you!

2023-10-23 08:03 UTC, RubelOS commented on Exercises/JuliusDralle/exercises_03.py
> +}
I gave Copyright to ChatGPT for creating those values. Thank you!

2023-10-23 08:04 UTC, RubelOS commented on Exercises/JuliusDralle/exercises_03.py
> +    "02" : "2",
What exactly do you mean with this comment?

2023-10-23 09:08 UTC, RubelOS commented on Exercises/JuliusDralle/exercises_03.py
> +        return(cardtype_dict[self.card_type], suits_dict[self.card_suite])
It cannot be out of range. The Deck iterates through two dictionaries which are just beind send over to the card objects

2023-10-23 21:44 UTC, GeFritz requested changes
Just change line 26 then done. Sorry if i am being strict but am just doing my job. Very nice idea with chat gpt tho.

2023-10-24 08:33 UTC, GeFritz approved these changes

2023-11-10 07:36 UTC, merged