Week 2 Utku Acikel
dhbw-ma-ppp/ppp-2023 pull request #63
Opened 2023-10-20 22:29 UTC by UtkuDHBW

Please review

2023-10-21 07:38 UTC, atrejut commented
remember to add the label for each week please :)

2023-10-24 07:51 UTC, LeMixer requested changes

2023-10-24 07:51 UTC, LeMixer commented on Exercises/Utku Acikel/exercises_02.py
> +def sim_computer(opcode):
Naming the variable `opcode` can be very misleading since the task describes opcode as the following:

> this (first) value will contain an 'opcode'. Valid opcodes are 1, 2 or 99.

Therefore only every fourth element in the commands list is considered an opcode.
Otherwise the solution looks good.

2023-10-24 07:51 UTC, LeMixer commented on Exercises/Utku Acikel/exercises_02.py
> +        elif len(arg) == 1:
From my understanding of the task '5' is also a string, which contains just one character, regardless if the the string can be interpreted as a number. In your implementation a string can only either be interpreted as a number *or* be a one char string.

2023-10-24 10:26 UTC, UtkuDHBW commented on Exercises/Utku Acikel/exercises_02.py
> +        elif len(arg) == 1:
In my understanding, I thought that numbers also with 1 character should be only interpreted as a number. But I think either way is right.

2023-10-24 11:13 UTC, LeMixer approved these changes

2023-10-24 21:33 UTC, merged

2023-10-25 05:38 UTC, atrejut commented
please only merge after we had a chance to discuss the solutions (in the wednesday class)

2023-10-25 05:39 UTC, UtkuDHBW commented
Oh okay sorry, i thougt that we should merge before wednesday.