Philipp Kirschke exercise03.py completed
dhbw-ma-ppp/ppp-2023 pull request #76
Opened 2023-10-25 13:54 UTC by The-Linux-User

Count of numbers matching criteria: 1306

2023-10-25 15:46 UTC, TrueEsel requested changes
Please add the test cases for the Skat deck and the return value for the third task. Its nothing major but still part of the tasks, should be an easy fix :)

2023-10-25 15:46 UTC, TrueEsel commented on Exercises/Philipp Kirschke/exercises_03.py
> +        if (number[index] == number[index+1] and number.count(number[index]) == 2):
since the numbers checked here are already sorted number[index] == number[index+1] is unnecessary. The right part of the and statement for itself yields the same result.

2023-10-25 15:46 UTC, TrueEsel commented on Exercises/Philipp Kirschke/exercises_03.py
> +class Deck:
In my opinion Deck is not a good name for this class since the skat class represents a card deck too

2023-10-25 15:46 UTC, TrueEsel commented on Exercises/Philipp Kirschke/exercises_03.py
> +class skat:
classes should start with an uppercase letter

2023-10-25 15:46 UTC, TrueEsel commented on Exercises/Philipp Kirschke/exercises_03.py
> +# Write some code to test the functionality of both kinds of decks. (You can use `assert` to make sure your classes behave the way you expect them to.)
the test cases for the Skat class are missing

2023-10-25 15:46 UTC, TrueEsel commented on Exercises/Philipp Kirschke/exercises_03.py
> +cardIndex = input("Enter the index of the card you want to see or press enter to see all cards in the deck: ")
nice test case, that lets the user pick the card

2023-10-25 15:46 UTC, TrueEsel commented on Exercises/Philipp Kirschke/exercises_03.py
> +    print(numberCount)
checkNumber should return the number, not just print it

2023-10-25 15:46 UTC, TrueEsel commented on Exercises/Philipp Kirschke/exercises_03.py
> +def checkIncrease(number):
interesting way to check if the number is increasing from left to right

2023-10-25 15:49 UTC, TrueEsel commented on Exercises/Philipp Kirschke/exercises_03.py
> +class skat:
you could also let skat inherit from deck since its a special case of the french deck but your code works too

2023-10-26 07:37 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_03.py
> +        if (number[index] == number[index+1] and number.count(number[index]) == 2):
Removed the redundant code

2023-10-26 07:38 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_03.py
> +class Deck:
Changed the name to FrenchDeck

2023-10-26 07:38 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_03.py
> +class skat:
Changed the class name to uppercase, this was a typo

2023-10-26 07:38 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_03.py
> +# Write some code to test the functionality of both kinds of decks. (You can use `assert` to make sure your classes behave the way you expect them to.)
Added the same user defined test cases that the FrenchDeck has

2023-10-26 07:39 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_03.py
> +cardIndex = input("Enter the index of the card you want to see or press enter to see all cards in the deck: ")
Thanks!

2023-10-26 07:39 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_03.py
> +    print(numberCount)
Added return statement

2023-10-26 07:39 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_03.py
> +def checkIncrease(number):
Could've also done it the other way around, but while having the flu and fever this seemed like the better method, I don't know why XD

2023-10-27 15:50 UTC, TrueEsel requested changes
Code is looking good, aside from the mistakes in the Skat Test. Fix that and your finished :)

2023-10-27 15:50 UTC, TrueEsel commented on Exercises/Philipp Kirschke/exercises_03.py
> +scatdeck = FrenchDeck()
your variable scatdeck is an object of FrenchDeck, not of Skat.

2023-10-27 15:50 UTC, TrueEsel commented on Exercises/Philipp Kirschke/exercises_03.py
> +elif (int(cardIndex) > 51):
since a skat deck has less cards than a french deck this condition is no longer working how its supposed to. If I search for the card at index 51 this will give me an IndexError

2023-11-02 08:04 UTC, The-Linux-User commented on Exercises/Philipp Kirschke/exercises_03.py
> +elif (int(cardIndex) > 51):
Both of the issues should be fixed now

2023-11-02 20:40 UTC, TrueEsel approved these changes
looks good now :)

2023-11-03 07:42 UTC, merged