Paul seidel exercise03
dhbw-ma-ppp/ppp-2023 pull request #77
Opened 2023-10-25 13:55 UTC by paulseidel08

Task 03 is ready to be reviewed. I hope, theres nothin doubled now.

2023-10-25 14:54 UTC, joh-lin reviewed
All in all I really like how you implemented the card deck. The sequence-like behaviour for your was correctly implemented and commented. 
A possible improvement for your code would be to make both french_card_deck and skat_deck inherit from a base class, so you could reuse code. The functionality of your sequence behaviour could also have been tested more thoroughly.
 For future projects please remember that class names should be written in pascal case like "Card" or "FrenchCardDeck".

2023-10-25 15:04 UTC, joh-lin requested changes
I liked part 1 and 2. Part 3 needs some fixing.

2023-10-25 15:04 UTC, joh-lin commented on Exercises/PaulSeidel/PSeidel_exercises_03.py
> +print(str(num_counter(min = 134564, max = 585159))) # finds 331261 numbers
Your solution for part 3 doesn't do exactly what the task requires. It also returns an incorrect solution value.

2023-10-27 06:33 UTC, paulseidel08 commented on Exercises/PaulSeidel/PSeidel_exercises_03.py
> +print(str(num_counter(min = 134564, max = 585159))) # finds 331261 numbers
To-Dos for myself:
- It's not checking, if the numbers are next to each other (there should be at least two next to each other)
- It's not checking, if the numbers are sorted

2023-10-27 06:36 UTC, joh-lin commented on Exercises/PaulSeidel/PSeidel_exercises_03.py
> +print(str(num_counter(min = 134564, max = 585159))) # finds 331261 numbers
Try adding the check if they are sorted first. It might already solve the problem.

2023-10-27 08:34 UTC, paulseidel08 commented on Exercises/PaulSeidel/PSeidel_exercises_03.py
> +print(str(num_counter(min = 134564, max = 585159))) # finds 331261 numbers
👍

2023-11-01 17:20 UTC, joh-lin approved these changes

2023-11-08 18:31 UTC, merged