Jan Merz Exercise 03
dhbw-ma-ppp/ppp-2023 pull request #78
Opened 2023-10-25 14:48 UTC by TrueEsel

Return value of task 3: 1306

2023-10-27 06:55 UTC, LeMixer requested changes
Looks good in general. Please revisit the lines I've commented:

2023-10-27 06:55 UTC, LeMixer commented on Exercises/JanMerz/exercises_03.py
> +    def __get__(self, index):
This does not implement indexing. However the task states you should be able to index the card deck to receive a card in the following manner: `card_at_index = deck[index]`
Try using __getitem__ instead.

2023-10-27 06:55 UTC, LeMixer commented on Exercises/JanMerz/exercises_03.py
> +    suits = ["Diamonds", "Hearts", "Spadess", "Clubs"]
Spades

2023-10-27 06:55 UTC, LeMixer commented on Exercises/JanMerz/exercises_03.py
> +print(french_deck)
Not sure why you are printing the deck twice. The second print statement shows that the deck is in fact iterable, but the first print just clutters the console.

2023-10-27 16:03 UTC, TrueEsel commented on Exercises/JanMerz/exercises_03.py
> +    suits = ["Diamonds", "Hearts", "Spadess", "Clubs"]
Fixed the Typo

2023-10-27 16:04 UTC, TrueEsel commented on Exercises/JanMerz/exercises_03.py
> +    def __get__(self, index):
implemented indexing. Thanks for the tip :)

2023-10-29 18:07 UTC, LeMixer approved these changes
Looks Good

2023-11-10 07:32 UTC, merged