Final Exercise_03
dhbw-ma-ppp/ppp-2023 pull request #82
Opened 2023-10-26 08:05 UTC by CorvinAn97

2023-10-26 08:17 UTC, The-Linux-User requested changes
The count of numbers from task 3 should be mentioned in your pull request

2023-10-26 08:19 UTC, CorvinAn97 commented
> The count of numbers from task 3 should be mentioned in your pull request

fixed that. :)

2023-10-26 08:19 UTC, The-Linux-User approved these changes
Requested changes implemented

2023-10-26 08:56 UTC, thecodingcube77 reviewed
Solid solution. Very much blank lines for some reason.

2023-10-26 08:56 UTC, thecodingcube77 commented on Exercises/Corvin Ansorge/exercises_03.py
> +import select
This import is never used and should be removed.

2023-10-26 08:56 UTC, thecodingcube77 commented on Exercises/Corvin Ansorge/exercises_03.py
> +    assert frenchdeck.cards[51] == Card("Ace", "clubs")
I think the task requires us to implement sequence behavior to the CardDeck classes so that you can index the CardDeck-object directly like this: `frenchdeck[0]`. This should result in `Card("2", "diamonds")` in your case.

2023-10-26 08:56 UTC, thecodingcube77 commented on Exercises/Corvin Ansorge/exercises_03.py
> +            if num_str[i] == num_str[i + 1] and (i == 0 or num_str[i - 1] != num_str[i]) and (i + 2 == len(num_str) or num_str[i + 2] != num_str[i]):
This if is logically completely fine as it does exactly what you need. But it is quite an overcomplication in my opinion. When you think about it, you don't actually need to verify that the group of 2 digits has no third digit in front or behind it. This is because all the same digits are next to each other when the digits are in order, so you only have to test if there is one digit that is there exactly 2 times in your number.

2023-10-27 07:05 UTC, CorvinAn97 commented on Exercises/Corvin Ansorge/exercises_03.py
> +import select
Thanks for the reminder!

2023-10-27 07:06 UTC, CorvinAn97 commented on Exercises/Corvin Ansorge/exercises_03.py
> +    assert frenchdeck.cards[51] == Card("Ace", "clubs")
Changed that! :)

2023-10-27 07:06 UTC, CorvinAn97 commented on Exercises/Corvin Ansorge/exercises_03.py
> +            if num_str[i] == num_str[i + 1] and (i == 0 or num_str[i - 1] != num_str[i]) and (i + 2 == len(num_str) or num_str[i + 2] != num_str[i]):
Good point. I also changed there a bit

2023-10-27 07:35 UTC, thecodingcube77 commented on Exercises/Corvin Ansorge/exercises_03.py
> +        if str(i)*2 in number and str(i)*3 not in number:
That is a very interesting way to test for the pair of digits

2023-11-03 07:44 UTC, merged