Woche03 AUfgaben
dhbw-ma-ppp/ppp-2023 pull request #88
Opened 2023-10-27 06:32 UTC by TomKnoden

There are changes to be made to the file

2023-11-01 13:36 UTC, s231365 requested changes
Good ideas, but you need to make some changes, because in number 3 your result is wrong.

2023-11-01 13:36 UTC, s231365 commented on Exercises/Tom_Knoden/Woche03/Woche_03_Aufgaben.py
> +
maybe you could do some testcases to test the functionality of your code

2023-11-01 13:36 UTC, s231365 commented on Exercises/Tom_Knoden/Woche03/Woche_03_Aufgaben.py
> +            if num_str[i] == num_str[i + 1]:
you also include numbers like 579999, which is incorrect. there should only be two 9's like 567899.  You need to check the third digits also.

2023-11-01 13:36 UTC, s231365 commented on Exercises/Tom_Knoden/Woche03/Woche_03_Aufgaben.py
> +    def __str__(self):
this not a string representation. it gives the storage position. since this is a dunder method you should use __str__ for string representation.

2023-11-01 13:36 UTC, s231365 commented on Exercises/Tom_Knoden/Woche03/Woche_03_Aufgaben.py
> +class skat_deck:
Here you could use inheritance. this would shorten your code, because you sont need to write the funtions twice

2023-11-18 09:29 UTC, atrejut commented
@TomKnoden please try to get this old PR merged...

2023-11-22 10:10 UTC, fabischw requested changes
Please remove the tasks for week 4 from this PR and address changes requested by @s231365 .

2023-11-28 22:16 UTC, closed without merging